name: Daily Research Update Bot

on:
  schedule:
    - cron: '0 11 * * *' # 미동부 아침 6시
  workflow_dispatch: 

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write 
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install Dependencies
        # pydrive2와 oauth2client를 명시적으로 설치해야 합니다.
        run: |
          pip install requests pydrive2 oauth2client

      - name: Run Script
        env:
          # Google Drive 연동을 위해 Secrets에 저장된 환경 변수를 불러옵니다.
          GDRIVE_SERVICE_ACCOUNT: ${{ secrets.GDRIVE_SERVICE_ACCOUNT }}
          GDRIVE_FOLDER_ID: ${{ secrets.GDRIVE_FOLDER_ID }}
        run: python paper_scraper.py

      - name: Commit and Push Changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Auto-update: $(date +'%Y-%m-%d') Research Papers" || exit 0
          git push
